Feature/lig 171 developpement merchantselectoffertypepage
Ligne8/AgoraPulse-Application pull request #60
Opened 2024-11-18 18:24 UTC by Tim-drd

Les petites modif par rapport à la maquette (image différentes ...) ont été validé par Mathieu

2024-11-18 23:26 UTC, Ronan-pdr commented
Est-ce que tu peux utiliser @expo/vector-icons plutôt que fortawesome?

2024-11-18 23:27 UTC, Ronan-pdr requested changes

2024-11-18 23:27 UTC, Ronan-pdr commented on app/Merchant/pages/SelectOfferTypePage.tsx
> +import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
Est-ce que tu peux utiliser @expo/vector-icons plutôt que fortawesome?

2024-11-19 10:09 UTC, Tim-drd commented on app/Merchant/pages/SelectOfferTypePage.tsx
> +import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
@Ronan-pdr done

2024-11-27 13:55 UTC, Ronan-pdr approved these changes

2024-11-27 13:55 UTC, merged